### PR TITLE
Change dockfile for only supporting sigmf ver1.0.0

### PR DESCRIPTION
**Pull request by LawsonGu**
As the Sigmf upgrade, there would be an "Assertion error" if users use sigmf newer than 1.0.0
image

This pull request is based on this issue. When build docker, would install only sigmf version same as 1.0.0

### CODE REVIEW

**Comment by Abdo-Gaber** [comment]
Hi @LawsonGu : great comment, we changed the getting started guide to use only SigMF 1.0.0 until we check the error in case of using SigMF 1.1.0 assert meta.validate but we did change the docker file. For the moment, on your side to go forward, either install SigMF 1.1.0 or disable this line of code in the write to SigMF function

**Comment by LawsonGu** [comment]
Do you think we need to merge this change into main at this moment?

**Comment by Abdo-Gaber** [comment]
@LawsonGu : Sure, it is clear, I will merge it. Thanks for taking care.

**Comment by Abdo-Gaber** [comment]
@LawsonGu : you can delete the branch or keep it if you still need it.

**Pull request merged**
